name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: List build directory contents
        run: ls -la build || echo "Build directory not found"
      - name: List build/_app directory contents
        run: ls -la build/_app || echo "Build/_app directory not found"
      - name: List build/_app/immutable directory contents
        run: ls -la build/_app/immutable || echo "Build/_app/immutable directory not found"
      - name: Create .nojekyll file
        run: touch build/.nojekyll
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'
          retention-days: 1
          name: github-pages
      - name: Debug artifact
        run: |
          echo "Artifact ID: ${{ steps.upload.outputs.artifact_id }}"
          echo "Artifact URL: ${{ steps.upload.outputs.artifact_url }}"
          echo "Artifact name: ${{ steps.upload.outputs.artifact_name }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages 